### ISSUE TITLE
Plugin code assumes asset directory location

### ISSUE THREAD

**Issue by gurpal2000** [jangabrielsson/TQAE#3]
There is a blog by Joep. As per https://docs.joepverhaeg.nl/hc3-tqae/ templates should be visible under the sub-menu.

On a vanilla Windows install, there are no items on the sub-menu.
The console says "Asset directory set to '\\.zbstudio\tqae\' even though I have files located under "c:\users\xxxxx\\.zbstudio\..."

In TQAEplugin.lua, it is assuming that OS env vars HOME or TQAEASSETS are defined.

`assetDir = (os.getenv('HOME')  or '')..ps..".zbstudio"..ps.."tqae"..ps`

The instructions on the blog omit this information.

Solutions:
- Fix the blog; add in missing hint
- Submit a PR, with OS agnostic check. Tactical - if Windows you could use "USERPROFILE".

**Comment by jangabrielsson** [comment]
Thanks, I totally missed your patch. I can't remember seeing any email notification either.
Anyway, I have merged it with the code -
Not having or testing on Windows makes it easy to miss stuff like this.
 thanks!
